// <auto-generated />
using API.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20190923194206_initial4")]
    partial class initial4
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("API.Models.Cotizacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Fecha");

                    b.Property<int?>("MonedaId");

                    b.Property<decimal>("Precio");

                    b.HasKey("Id");

                    b.HasIndex("MonedaId");

                    b.ToTable("Cotizaciones");
                });

            modelBuilder.Entity("API.Models.ErrorDetails", b =>
                {
                    b.Property<int>("StatusCode")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Message");

                    b.HasKey("StatusCode");

                    b.ToTable("ErrorDetails");
                });

            modelBuilder.Entity("API.Models.Moneda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Codigo");

                    b.Property<string>("Descripcion");

                    b.HasKey("Id");

                    b.ToTable("Monedas");
                });

            modelBuilder.Entity("API.Models.Sindicato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Descripcion");

                    b.HasKey("Id");

                    b.ToTable("Sindicatos");
                });

            modelBuilder.Entity("API.Models.Sueldo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("Bono");

                    b.Property<DateTime>("Fecha");

                    b.Property<decimal>("SueldoBruto");

                    b.Property<decimal>("SueldoNeto");

                    b.Property<int?>("TrabajoId");

                    b.Property<string>("UsuarioEmail");

                    b.HasKey("Id");

                    b.HasIndex("TrabajoId");

                    b.HasIndex("UsuarioEmail");

                    b.ToTable("Sueldos");
                });

            modelBuilder.Entity("API.Models.Trabajo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("RazonSocial");

                    b.Property<int?>("SindicatoId");

                    b.HasKey("Id");

                    b.HasIndex("SindicatoId");

                    b.ToTable("Trabajos");
                });

            modelBuilder.Entity("API.Models.Usuario", b =>
                {
                    b.Property<string>("Email")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("TrabajoId");

                    b.HasKey("Email");

                    b.HasIndex("TrabajoId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("API.Models.Cotizacion", b =>
                {
                    b.HasOne("API.Models.Moneda", "Moneda")
                        .WithMany()
                        .HasForeignKey("MonedaId");
                });

            modelBuilder.Entity("API.Models.Sueldo", b =>
                {
                    b.HasOne("API.Models.Trabajo", "Trabajo")
                        .WithMany()
                        .HasForeignKey("TrabajoId");

                    b.HasOne("API.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioEmail");
                });

            modelBuilder.Entity("API.Models.Trabajo", b =>
                {
                    b.HasOne("API.Models.Sindicato", "Sindicato")
                        .WithMany()
                        .HasForeignKey("SindicatoId");
                });

            modelBuilder.Entity("API.Models.Usuario", b =>
                {
                    b.HasOne("API.Models.Trabajo", "Trabajo")
                        .WithMany()
                        .HasForeignKey("TrabajoId");
                });
#pragma warning restore 612, 618
        }
    }
}
